### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by dansroka** [VineCode/PHPLint.novaextension#1] opened 2020-08-28 19:01 UTC
When I install the extension "PHPLint" into Nova v1.0b19, I immediately receive the following error:

```
PHPLint[14:14:31.006000] Extension encountered an uncaught exception:
/Users/sroka/Library/Application Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js (Line 49, Column 0)
TypeError: undefined is not an object (evaluating 'message.replace')
    file:///Users/sroka/Library/Application%20Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js:49:34

```

No other extensions are installed — this is a new and clean installation of Nova b19.

**Comment by thebigreason** [comment] 2020-09-03 21:55
I am getting the same error:

`Extension encountered an uncaught exception:
/Users/marke/Library/Application Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js (Line 49, Column 0)
TypeError: undefined is not an object (evaluating 'message.replace')
    file:///Users/marke/Library/Application%20Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js:49:34`

Using Nova v1.0b20.

**Comment by danielvesma** [comment] 2020-09-04 12:46
Same:

`Extension encountered an uncaught exception:
/Users/daniel/Library/Application Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js (Line 49, Column 0)
TypeError: undefined is not an object (evaluating 'message.replace')
    file:///Users/daniel/Library/Application%20Support/Nova/Extensions/vinecode.PHPLint/Scripts/main.js:49:34`

**Comment by vinecode-andy** [comment] 2020-09-10 12:39
I couldn't reproduce this in my setup but have tried to catch the error. Could you let me know if this is resolved in v0.2

**Comment by dansroka** [comment] 2020-09-10 13:04
I updated to v0.2, and restarted Nova. I no longer get the error after it installs or when it first loads. But if I create and validate a PHP with an obvious error, I get a new error message.

For example, testing this code:
`<?php
echo "hello
?>
`
Produced this error in the Extensions Console: `Errors parsing /Volumes/Sparky/Users/sroka/Sites/danielsroka/test.php`.
(And no validation issues get posted in the Issues pane.) 

My setup:
Nova v1.0, running on Mac OS 10.15.6, using the standard Catalina installation of PHP (located at /usr/bin/php). FYI, the PHPLint running in Coda v2 (via PHPPlugin v4.2) is working as expected.

**Comment by oliveratgithub** [comment] 2020-09-17 19:38
> For example, testing this code:
> `<?php echo "hello ?> `
> Produced this error in the Extensions Console: `Errors parsing /Volumes/Sparky/Users/sroka/Sites/danielsroka/test.php`.
> (And no validation issues get posted in the Issues pane.)

@dansroka I got the same error until I manually fixed the path to the php executable, as documented in #3

**Comment by dansroka** [comment] 2020-09-17 20:30
I am using the default PHP installation for Catalina, located at:
`/usr/bin/php`
I checked in the UserConfiguration.json file, and it seems to be escaped correctly:
`"VineCode.PHPLint.execPath" : "\/usr\/bin\/php"`

**Comment by dansroka** [comment] 2020-10-01 23:31
When I save a PHP file, I am still getting this error in the Debug Pane:
```
PHPLint[19:30:05.705000] Errors parsing /Volumes/Sparky/Users/sroka/Sites/danielsroka/advice.php
```

PHPLint v0.3.1
Nova v1.2

**Comment by vinecode-andy** [comment] 2020-10-16 15:21
@dansroka In Terminal could you run `/usr/bin/php --version` and let me know the output. I am running PHP 7.3.11 (cli) and still can't seem to re-produce this.

**Comment by vinecode-andy** [comment] 2020-10-16 15:24
I will close this as it appears to be the same issue and information as #6

**Closed as completed** 2020-10-16 15:25 UTC
Labels: bug
